# Generated by Django 5.2.3 on 2025-06-23 07:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("bookings", "0001_initial"),
        ("schedules", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="schedule",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bookings",
                to="schedules.schedule",
            ),
        ),
    ]
